modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:      
      valid_status_codes: []
      method: GET
      preferred_ip_protocol: "ipv4"
      tls_config:
        insecure_skip_verify: true
      no_follow_redirects: true